apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: php-host
  name: php-host
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: php-host
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: php-host
    spec:
      containers:
      - image: joanatanasoff/dof-php:%IMAGE-PLACEHOLDER%
        imagePullPolicy: ""
        name: php-host
        volumeMounts:
        - name: site
          mountPath: /site
          subPath: "app"
          readonly: true
        ports:
        - containerPort: 9000
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - name: site
        gitRepo:
          repository: https://github.com/joanatanasoff/dof-exam.git
          revision: master
          directory: .  
status: {}
